# Auto-generated by tuner_v2.py
# Learned positional weights (material values are fixed)
#
# These weights predict the RESIDUAL (score - material)
# so they represent pure positional value.

INTERCEPT = 23.9545

# Fixed material values (not learned)
MATERIAL_PAWN = 100
MATERIAL_KNIGHT = 320
MATERIAL_BISHOP = 330
MATERIAL_ROOK = 500
MATERIAL_QUEEN = 900

# Learned positional weights
POSITIONAL_WEIGHTS = {
    'rook_on_7th': 81.19,
    'king_open_file_mg': -65.36,
    'bishop_pair': 58.83,
    'tempo': 37.49,
    'rook_open_file': 35.32,
    'passed_pawns': 20.84,
    'doubled_pawns': -19.58,
    'rook_semi_open': 18.58,
    'isolated_pawns': -13.70,
    'king_shield_mg': 6.51,
    'king_tropism_mg': 5.46,
    'mobility_mg': 5.03,
    'king_centralization_eg': -3.44,
    'center_control_mg': 3.34,
    'connected_rooks': 2.32,
    'backward_pawns': -1.86,
    'knight_outpost': 1.56,
    'pawn_chains': 1.32,
}
